In [2]:
import mlflow
import pandas as pd
import mlflow.sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import numpy as np

c:\Users\KARTHIK\miniconda3\envs\capstone-mlops-proj\lib\site-packages\mlflow\utils\requirements_utils.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources  # noqa: TID251

In [3]:
df = pd.read_csv('IMDB.csv')
df = df.sample(500)
df.to_csv('data.csv', index=False)
df.head()

                                                review sentiment
38   I don't understand why this movie was released...  negative
188  Whatever rating I give BOOM is only because of...  negative
19   I tend to get furious when hearing about Lucio...  positive
612  Viva Variety was a unique hybrid program that ...  positive
36   My 15 year old daughter asked me to watch this...  negative

In [4]:
# data preprocessing

# Define text preprocessing functions
def lemmatization(text):
    """Lemmatize the text."""
    lemmatizer = WordNetLemmatizer()
    text = text.split()
    text = [lemmatizer.lemmatize(word) for word in text]
    return " ".join(text)

def remove_stop_words(text):
    """Remove stop words from the text."""
    stop_words = set(stopwords.words("english"))
    text = [word for word in str(text).split() if word not in stop_words]
    return " ".join(text)

def removing_numbers(text):
    """Remove numbers from the text."""
    text = ''.join([char for char in text if not char.isdigit()])
    return text

def lower_case(text):
    """Convert text to lower case."""
    text = text.split()
    text = [word.lower() for word in text]
    return " ".join(text)

def removing_punctuations(text):
    """Remove punctuations from the text."""
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = text.replace('؛', "")
    text = re.sub('\s+', ' ', text).strip()
    return text

def removing_urls(text):
    """Remove URLs from the text."""
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def normalize_text(df):
    """Normalize the text data."""
    try:
        df['review'] = df['review'].apply(lower_case)
        df['review'] = df['review'].apply(remove_stop_words)
        df['review'] = df['review'].apply(removing_numbers)
        df['review'] = df['review'].apply(removing_punctuations)
        df['review'] = df['review'].apply(removing_urls)
        df['review'] = df['review'].apply(lemmatization)
        return df
    except Exception as e:
        print(f'Error during text normalization: {e}')
        raise

In [5]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KARTHIK\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
df = normalize_text(df)
df.head()

                                                review sentiment
38   understand movie released looked like somethin...  negative
188  whatever rating give boom superb location phot...  negative
19   tend get furious hearing lucio fulci s reputat...  positive
612  viva variety unique hybrid program parody trib...  positive
36   year old daughter asked watch movie cable tv s...  negative

In [7]:
df['sentiment'].value_counts()

sentiment
negative    258
positive    242
Name: count, dtype: int64

In [8]:
x = df['sentiment'].isin(['positive','negative'])
df = df[x]

In [9]:
df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})
df.head()

                                                review  sentiment
38   understand movie released looked like somethin...          0
188  whatever rating give boom superb location phot...          0
19   tend get furious hearing lucio fulci s reputat...          1
612  viva variety unique hybrid program parody trib...          1
36   year old daughter asked watch movie cable tv s...          0

In [10]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [15]:
vectorizer = CountVectorizer(max_features=50)
X = vectorizer.fit_transform(df['review'])
y = df['sentiment']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [17]:
import dagshub

mlflow.set_tracking_uri('https://dagshub.com/karthik14344/MLOps-Capstone-Project.mlflow')
dagshub.init(repo_owner='karthik14344', repo_name='MLOps-Capstone-Project', mlflow=True)

# mlflow.set_experiment("Logistic Regression Baseline")
mlflow.set_experiment("Logistic Regression Baseline")

Initialized MLflow to track repo "karthik14344/MLOps-Capstone-Project"

2026-04-09 20:49:57,574 - INFO - Initialized MLflow to track repo "karthik14344/MLOps-Capstone-Project"

Repository karthik14344/MLOps-Capstone-Project initialized!

2026-04-09 20:49:57,578 - INFO - Repository karthik14344/MLOps-Capstone-Project initialized!

<Experiment: artifact_location='mlflow-artifacts:/512507d0999148a3a29c9ee26e1ad11c', creation_time=1775744676535, experiment_id='0', last_update_time=1775744676535, lifecycle_stage='active', name='Logistic Regression Baseline', tags={'mlflow.experimentKind': 'custom_model_development'}>

In [18]:
import mlflow
import logging
import os
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

logging.info("Starting MLflow run...")

with mlflow.start_run():
    start_time = time.time()
    
    try:
        logging.info("Logging preprocessing parameters...")
        mlflow.log_param("vectorizer", "Bag of Words")
        mlflow.log_param("num_features", 50)
        mlflow.log_param("test_size", 0.20)

        logging.info("Initializing Logistic Regression model...")
        model = LogisticRegression(max_iter=1000)  # Increase max_iter to prevent non-convergence issues

        logging.info("Fitting the model...")
        model.fit(X_train, y_train)
        logging.info("Model training complete.")

        logging.info("Logging model parameters...")
        mlflow.log_param("model", "Logistic Regression")

        logging.info("Making predictions...")
        y_pred = model.predict(X_test)

        logging.info("Calculating evaluation metrics...")
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        logging.info("Logging evaluation metrics...")
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

        logging.info("Saving and logging the model...")
        mlflow.sklearn.log_model(model, "model")

        # Log execution time
        end_time = time.time()
        logging.info(f"Model training and logging completed in {end_time - start_time:.2f} seconds.")

        # Save and log the notebook
        # notebook_path = "exp1_baseline_model.ipynb"
        # logging.info("Executing Jupyter Notebook. This may take a while...")
        # os.system(f"jupyter nbconvert --to notebook --execute --inplace {notebook_path}")
        # mlflow.log_artifact(notebook_path)

        # logging.info("Notebook execution and logging complete.")

        # Print the results for verification
        logging.info(f"Accuracy: {accuracy}")
        logging.info(f"Precision: {precision}")
        logging.info(f"Recall: {recall}")
        logging.info(f"F1 Score: {f1}")

    except Exception as e:
        logging.error(f"An error occurred: {e}", exc_info=True)

2026-04-09 20:50:01,791 - INFO - Starting MLflow run...

2026-04-09 20:50:02,586 - INFO - Logging preprocessing parameters...
2026-04-09 20:50:04,119 - INFO - Initializing Logistic Regression model...
2026-04-09 20:50:04,119 - INFO - Fitting the model...
2026-04-09 20:50:04,150 - INFO - Model training complete.
2026-04-09 20:50:04,150 - INFO - Logging model parameters...
2026-04-09 20:50:04,567 - INFO - Making predictions...
2026-04-09 20:50:04,568 - INFO - Calculating evaluation metrics...
2026-04-09 20:50:04,579 - INFO - Logging evaluation metrics...
2026-04-09 20:50:06,477 - INFO - Saving and logging the model...
c:\Users\KARTHIK\miniconda3\envs\capstone-mlops-proj\lib\site-packages\_distutils_hack\__init__.py:15: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
c:\Users\KARTHIK\miniconda3\envs\capstone-mlops-proj\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
2026/04/09 20:50:16 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.
2026-04-09 20:50:16,616 - INFO - Model training and logging completed in 14.03 seconds.
2026-04-09 20:50:16,621 - INFO - Accuracy: 0.64
2026-04-09 20:50:16,623 - INFO - Precision: 0.6
2026-04-09 20:50:16,624 - INFO - Recall: 0.6521739130434783
2026-04-09 20:50:16,626 - INFO - F1 Score: 0.625
2026/04/09 20:50:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run nosy-hog-556 at: https://dagshub.com/karthik14344/MLOps-Capstone-Project.mlflow/#/experiments/0/runs/e1a3224cde874dcea9d83e77ac2fdb30.
2026/04/09 20:50:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://dagshub.com/karthik14344/MLOps-Capstone-Project.mlflow/#/experiments/0.